### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by franknoe** [markovmodel/deeptime#7]
Hi Luca+Andreas. Installation fails for me. I don't know these packages that are required. Maybe some nonstandard stuff. Can you fix that?

```python
panda:vampnet noe$ python setup.py install
Couldn't find index page for 'setuptools_scm_git_archive' (maybe misspelled?)
No local packages or download links found for setuptools-scm-git-archive
Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    zip_safe=False)
  File "/Users/noe/anaconda/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/noe/anaconda/lib/python2.7/site-packages/setuptools/dist.py", line 221, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/Users/noe/anaconda/lib/python2.7/site-packages/setuptools/dist.py", line 245, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
  File "/Users/noe/anaconda/lib/python2.7/site-packages/pkg_resources.py", line 586, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/Users/noe/anaconda/lib/python2.7/site-packages/pkg_resources.py", line 831, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/Users/noe/anaconda/lib/python2.7/site-packages/pkg_resources.py", line 843, in obtain
    return installer(requirement)
  File "/Users/noe/anaconda/lib/python2.7/site-packages/setuptools/dist.py", line 295, in fetch_build_egg
    return cmd.easy_install(req)
  File "/Users/noe/anaconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 598, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-scm-git-archive')
```

**Comment by cclementi** [comment]
Installation fails for me too, with different errors:

### ```
Cecilia-13:35> python setup.py install
Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    zip_safe=False)
  File "/Users/cecilia/Software/miniconda2/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/Users/cecilia/Software/miniconda2/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/cecilia/Software/miniconda2/lib/python2.7/site-packages/setuptools/dist.py", line 336, in __init__
    _Distribution.__init__(self, attrs)
  File "/Users/cecilia/Software/miniconda2/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/Users/cecilia/Software/miniconda2/lib/python2.7/site-packages/setuptools/dist.py", line 470, in finalize_options
    ep.load()(self, ep.name, value)
  File "/Users/cecilia/Software/deeptime/vampnet/.eggs/setuptools_scm-1.15.6-py2.7.egg/setuptools_scm/integration.py", line 22, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/Users/cecilia/Software/deeptime/vampnet/.eggs/setuptools_scm-1.15.6-py2.7.egg/setuptools_scm/__init__.py", line 119, in get_version
    parsed_version = _do_parse(root, parse)
  File "/Users/cecilia/Software/deeptime/vampnet/.eggs/setuptools_scm-1.15.6-py2.7.egg/setuptools_scm/__init__.py", line 97, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % root)
LookupError: setuptools-scm was unable to detect version for '/Users/cecilia/Software/deeptime/vampnet'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

```

**Comment by cwehmeyer** [comment]
We are using automatised versioning for multiple packages within one repository and `vamp net/setup.py` seems to have a wrong setting.

**Comment by cwehmeyer** [comment]
OK, we checked that the package installs on OSX and Linux with the change introduced in #8.

Please note that not all dependencies can be installed automatically. You need to install [tensorflow-1.4](https://www.tensorflow.org/install) manually (either the GPU or CPU-only version).

@franknoe you nee to upgrade your python installation as `vampnet` requires Python3.
